### ISSUE TITLE
Option to disable TLS?

### ISSUE THREAD

**Issue by waj334** [GoogleCloudPlatform/iot-device-sdk-embedded-c#110]
I have a WINC1500 wifi coprocessor on my board and from my understanding it can already handle all TLS decoding/encoding internally. Is there currently a way to switch off the software side TLS since my wifi coprocessor renders it redundant?

**Comment by atigyi** [comment]
Yes, there is a way to switch off the software TLS.

Build the library with the following `make` paremeter:
`make PRESET=POSIX_UNSECURE_REL`

How the build system handles this? Check it in the [mt-presets.mk](https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/blob/master/make/mt-config/mt-presets.mk) 
The trick is to omit the [`tls_bsp` from the CONFIG](https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/blob/master/make/mt-config/mt-presets.mk#L22). This will leave out the [TLS sources from the build](https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/tree/master/src/libiotc/tls) + the [TLS BSP](https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/tree/master/src/bsp/tls/mbedtls), you can check the compiled file list during the build.

Knowing this should make you able to build "unsecure" client lib for any other platform (other than POSIX).

Please let me know if you have troubles solving this!

**Comment by waj334** [comment]
Thanks! I'll give it a try and let you know what happens.

**Comment by waj334** [comment]
It took a while, but it looks like this is going to work for me. Thanks @atigyi !

**Comment by atigyi** [comment]
👏  👏  👏  Very happy to hear that! Congratulations! You were able to turn off software TLS in the SDK and use the hardware TLS!! Great job!
