### ISSUE TITLE
Not null-terminated issue in message.topic with iotc_user_subscription_callback_t

### ISSUE THREAD

**Issue by csobrinho** [GoogleCloudPlatform/iot-device-sdk-embedded-c#111]
https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/blob/1c1bdcb12d408a7e93d3873824088e97c6283c8a/src/libiotc/iotc_user_sub_call_wrapper.c#L76 I believe this line of code introduced a very subtle bug that completely breaks some clients and could potentially crash the device.

The code I have that experiences this is here:
https://github.com/csobrinho/hydroponics/blob/master/main/network/mqtt.c#L149-L151

Here's how to reproduce it:
 - when a client subscribes to a topic, like the `/devices/{clientName}/config` it calls `iotc_subscribe` and passes a `iotc_user_subscription_callback_t`.
 - if everything works out, the server with reply with a `iotc_sub_call_type_t` `IOTC_SUB_CALL_SUBACK` for that subscription. It will also provide the `const iotc_sub_call_params_t *const params` `params->suback.topic` that is a **NULL terminated string** for the topic.
 - when a new message is arrives, the same callback will be invoked but this time with `IOTC_SUB_CALL_MESSAGE`. Here the user can access the `params->message.temporary_payload_data_length` and `params->message.temporary_payload_data` and the `params->message.topic`.

When a new message is received, hopefully we get a `IOTC_STATE_OK` and inside the `iotc_user_sub_call_wrapper`, the `publish.topic` will be constructed like so:
```
      params.message.topic = (const char*)msg->publish.topic_name->data_ptr;
```

Now here comes the problem. We are casting the `params.message.topic` to the `publish.topic_name->data_ptr` and this pointer is **NOT null terminated**. When we copy the data to that `publish.topic_name->data_ptr` (that is a `iotc_data_desc_t`) it will allocate to the nearest 32 bytes and zero them out. So any topic length from 1-31 will have:

```
  publish.topic_name->data_ptr = "/devices/{deviceName}/config"
  publish.topic_name->length = 1-31
  publish.topic_name->capacity = 32
```

Any 32 > topic < 64

```
  publish.topic_name->data_ptr = "/devices/{reallyBigDeviceName}/config"
  publish.topic_name->length = 33
  publish.topic_name->capacity = 64
```
Since the block is cleared during allocation, **at least one** NULL terminator will be there.

Now here comes the fun part. If the topic name is **exactly 32 or 64 or any multiple of 32 chars**, then `publish.topic_name->data_ptr` will have a `length = 32` and a `capacity = 32` meaning the topic will **NOT be null terminated**.

```
  publish.topic_name->data_ptr = "/devices/123456789abcdef0/config" <- no '\0', just random memory garbage
  publish.topic_name->length = 32
  publish.topic_name->capacity = 32
```

I was unfortunate enough to have this problem for several months on my prod device (`/devices/GreenMeanMachine/config`) without ever affecting my test device `/devices/GreenMeanMachine-test/config` because one has `32` chars and the other has `37`!

I can see a few options here:
 - on the corresponding function inside `iotc_data_desc.c` that actually allocates the `iotc_data_desc_t` that is used downstream, we can add +1 when we allocate a string. For instance the `iotc_make_desc_from_buffer_copy` (and other places where we clone a string) could become:
```
iotc_data_desc_t* iotc_make_desc_from_buffer_copy(unsigned const char* buffer,
                                                  size_t len) {
  assert(buffer != 0);

  iotc_state_t state = IOTC_STATE_OK;

  IOTC_ALLOC(iotc_data_desc_t, data_desc, state);
  data_desc->memory_type = IOTC_MEMORY_TYPE_MANAGED;

  IOTC_ALLOC_BUFFER_AT(unsigned char, data_desc->data_ptr, len + 1, state);
  memcpy(data_desc->data_ptr, buffer, len);

  data_desc->capacity = len + 1;
  data_desc->length = len;

  return data_desc;

err_handling:
  iotc_free_desc(&data_desc);
  return NULL;
}
```

This would translate in one more byte but each string will always be NULL terminated, no matter if you use the `iotc_data_desc_t->length` or not.

- duplicate the `publish->topic` string from the corresponding `iotc_data_desc_t` taking into consideration the full string + '\0' instead of casting the `msg->publish.topic_name->data_ptr` to a `const char*`. This would then need to be free'ed after the callback was called.

Happy to write a fix but need some direction on how to processed.
Thanks!

**Comment by csobrinho** [comment]
+ @sheindel

**Comment by atigyi** [comment]
Thanks for spotting this. And describing it in an easy-to-understand style, thx. As I see the problem is real. But let me share my understanding:
- `iotc_data_dest_t` is the "default" storage inside this library. This can contain any binary, string included. But apparently does not ensure zero termination in case string is stored. I would not alter this design.
- the problem we face with here is the `const char*` cast line assumes zero termination which isn't ensured ([all 2^n length strings](https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/blob/master/src/libiotc/iotc_data_desc.c#L167) will have this issue: no zero termination).
- the solution 1) would change the 0<= zeropad to 1<= zeropad for each `iotc_data_dest_t` even if it is not a string. Which solves the issue but there should be a less intrusive solutions. We could hit this path and try to pad with 1<= zeros only the string buffers, but then we should search for other places where this stringbuffer `const char*` cast is solved by your 2nd solution offer.
- you already guessed, I'd choose the second. What about adding these two new lines before [the `const char*` cast line](https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/blob/1c1bdcb12d408a7e93d3873824088e97c6283c8a/src/libiotc/iotc_user_sub_call_wrapper.c#L76)?
```
params.message.topic = (const char*)msg->publish.topic_name->data_ptr;         
                                                                               
in_state = iotc_data_desc_append_data_resize(msg->publish.topic_name, "\0", 1);
IOTC_CHECK_STATE(in_state);                                                    
                                                                               
params.message.topic = (const char*)msg->publish.topic_name->data_ptr;
```        

probably the empty string would do it too, but less readable:
```
in_state = iotc_data_desc_append_data_resize(msg->publish.topic_name, "", 1);
```                                       

This is just one version of your second solution idea. WDYT?

**Comment by sheindel** [comment]
@csobrinho wow good find, so sorry to have introduced this bug. I should have known better than to trust the data lengths in the cast. I honestly didn't even realize they were doing this boundary checking. It was interesting to dig into and see the buffer expansion strategy (I was still digging but @atigyi beat me to a solution!)

I initially came up with the same solution as you (perhaps modifying the `iotc_data_desc_will_it_fit` method to change the allowable boundaries), but yes, that might be too intrusive, so my vote would be for the solution you presented (appending the null character and resizing in this case)

```C
in_state = iotc_data_desc_append_data_resize(msg->publish.topic_name, "\0", 1);
IOTC_CHECK_STATE(in_state);                                                    
                                                                               
params.message.topic = (const char*)msg->publish.topic_name->data_ptr;
```

**Comment by csobrinho** [comment]
Yep, this was driving me nuts for months because it would show well at startup then it would show garbage. Then to make things worse, it would only happen on my prod device (ESP32) but not on my dev board (ESP32-S2). Of course, only the dev one had a JTAG debugger, obviously. I checked for memory corruptions, with and without external SPI ram, with and without HEAP tracking, you name it.

@atigyi I'm fine either way but I'm concerned that this issue might show up elsewhere. For instance in the `iotc_make_desc_from_string_copy` you will also have the same problem. You use `strlen` so the original buffer will have the '\0' (hopefully!!!) but then you copy only the string part, no '\0'. Should that function also be fixed, just to be safe?

Happy to cook that fix (2) for now or fix both at the same time. WDYT?

**Comment by csobrinho** [comment]
If we search for `char\*\).*[\.\>]+data_ptr` on `iot-device-sdk-embedded-c` we get (after we ignore two tests):

`iotc_data_desc.c`:
```
   params.message.topic = (const char*)msg->publish.topic_name->data_ptr;
```

`iotc_mqtt_parser.c`
```
   (*dst), (const char*)src->data_ptr + src->curr_pos, len_to_read));
   (*dst), (const char*)src->data_ptr + src->curr_pos, len_to_read));
```

So it seems that one is the only issue (right now!) because the second two have a `len_to_read` parameter.

**Comment by csobrinho** [comment]
#112 has the pull request.

**Comment by atigyi** [comment]
Thank you @csobrinho for hunting down this bug, thanks for explaining the issue clearly and thanks for implementing the fix!! 👍

**Comment by csobrinho** [comment]
Awesome, thanks!
