### ISSUE TITLE
Access denied when trying to build

### ISSUE THREAD

**Issue by tyczj** [GoogleCloudPlatform/iot-device-sdk-embedded-c#118]
I cloned the repo and its submodules then when I try to run the make command on the project I get Access denied errors and it just hangs.

I tried opening the windows command prompt as administrator and that made no difference

```
C:\Users\Jeff\Desktop\t4\iot-device-sdk-embedded-c>make
# Using build PRESET "POSIX_REL" to set CONFIG and TARGET variables:
.    IOTC_BSP_PLATFORM: [posix]
.    IOTC_BSP_TLS:      [mbedtls]
Access denied - C:/USERS/JEFF/DESKTOP/T4/IOT-DEVICE-SDK-EMBEDDED-C/SRC
File not found - -NAME
Access denied - C:/USERS/JEFF/DESKTOP/T4/IOT-DEVICE-SDK-EMBEDDED-C/SRC/TESTS
File not found - -NAME
! was unexpected at this time.
Access denied - C:/USERS/JEFF/DESKTOP/T4/IOT-DEVICE-SDK-EMBEDDED-C/SRC
File not found - -NAME
Access denied - C:/USERS/JEFF/DESKTOP/T4/IOT-DEVICE-SDK-EMBEDDED-C/SRC/TESTS
File not found - -NAME
```

I dont see what I am missing here?

**Comment by atigyi** [comment]
What I see in the logs there: it complains about
1) directory access denied and
2) file not found - -name

And
```
atigyi:~/.../iot-edge-sdk-embedded-c/make$ grep -R "\ \-name" .
./mt-config/tests/mt-gtest.mk:IOTC_GTEST_SOURCES := $(shell find $(LIBIOTC)/src -name "*_test.cc")
./mt-config/tests/mt-gtest.mk:IOTC_GTEST_SOURCES += $(shell find $(LIBIOTC)/src/tests -name "*.cc")
```
src and src/test folders match. I think this is the problem the Windows `make` complains about..."first". 

Let's not focus on this, but rather on Windows native build isn't supported by this SDK's make system. Please try with `cygwin` on Windows or rather use a linux distro (e.g. Ubuntu) to build this SDK.

**Comment by tyczj** [comment]
I had a feeling that I was going to have to use linux to build it, I will give that a try
