### ISSUE TITLE
Switch from private to public Travis CI

### ISSUE THREAD

**Issue by mbrukman** [GoogleCloudPlatform/iot-device-sdk-embedded-c#50]
Since this repo is now public, I think it's time to switch from private Travis CI:

* https://travis-ci.com/GoogleCloudPlatform/iot-device-sdk-embedded-c (note the **`.com`** domain)

to public Travis CI:

* https://travis-ci.org/GoogleCloudPlatform/iot-device-sdk-embedded-c (note the **`.org`** domain)

Currently, the .com domain shows the status, and the .org domain shows it's an inactive repository, so a repo admin needs to activate it on the .org domain by visiting the page above.

**Comment by atigyi** [comment]
PTAL at a blog post dated May 2, 2018: [Announcing support for open source projects on travis-ci.com](https://blog.travis-ci.com/2018-05-02-open-source-projects-on-travis-ci-com-with-github-apps)

"If you’re activating a new repository – either public or private – on Travis CI, please use travis-ci.com."
"You can continue to use both your travis-ci.org and travis-ci.com accounts as usual for now. Over the next several months, we’ll be migrating all travis-ci.org repositories and customers to travis-ci.com."

Considering this I think it is better to stay on `.com`. But, yes, in the past `.org` was dedicated to public repos, `.com` for privates, but this seems has been changed recently.

**Comment by mbrukman** [comment]
Thanks for the pointer to the blog post! Makes sense, and looks like we don't need to do anything here to address this.
