### ISSUE TITLE
"gtest" dependency doesn't seem to be documented

### ISSUE THREAD

**Issue by pfalcon** [GoogleCloudPlatform/iot-device-sdk-embedded-c#59]
I'm following the project README to build the project on Linux (I'm using Ubuntu 18.04). Specifically, I ran `make` in the top-level directory, followed by `make tests`. The latter failed mid-way:

~~~
[g++] /home/pfalcon/projects-3rdparty/Embedded/Zephyr/iot-device-sdk-embedded-c/obj/linux/tests/gtests/tests/iotc_openssl_utils.o
[g++] /home/pfalcon/projects-3rdparty/Embedded/Zephyr/iot-device-sdk-embedded-c/obj/linux/tests/gtests/libiotc/iotc_test.o
/home/pfalcon/projects-3rdparty/Embedded/Zephyr/iot-device-sdk-embedded-c/src//libiotc/iotc_test.cc:17:10: fatal error: gtest.h: No such file or directory
 #include "gtest.h"
          ^~~~~~~~~
compilation terminated.
~~~

Looks like the build process depends on "libgtest-dev" package to be installed on Ubuntu, but this fact doesn't seem to be documented.

**Comment by pfalcon** [comment]
> Looks like the build process depends on "libgtest-dev" package to be installed on Ubuntu, but this fact doesn't seem to be documented.

Well, nope... Looks like there's a git submodule for googletest which needs to be initialized. But again, I don't seem to see info about that in the README of elsewhere. Will keep looking...

**Comment by verkri** [comment]
Thanks Paul for reporting this issue.

Indeed, you need to initialize the git submodule by running:

`git submodule init`

I am going to follow-up with a change in the documentation.

**Comment by pfalcon** [comment]
> I am going to follow-up with a change in the documentation.

Thanks for the PR https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/pull/60!

**Comment by atigyi** [comment]
PR #60 has been merged to development branch.
