### ISSUE TITLE
The HOST connection URL in the configuration is not 'mqtt.googleapis.com'

### ISSUE THREAD

**Issue by ja-mescher** [GoogleCloudPlatform/iot-device-sdk-embedded-c#64]
The device configuration is setup to connect to 'mqtt.2030.ltsapis.goog:8883'. What is this URL and why isn't the connection configured to 'mqtt.googleapis.com:8883'?

https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/blob/a26ee5ec79ad61eaf58461a1ef870f217e08b9d4/src/libiotc/iotc_config.h#L45-L48

**Comment by DellaBitta** [comment]
Please see my response to [Issue 65](https://github.com/GoogleCloudPlatform/iot-device-sdk-embedded-c/issues/65).  Thanks!
