### ISSUE TITLE
connection closed - reason 17 : !

### ISSUE THREAD

**Issue by dhruvsus** [GoogleCloudPlatform/iot-device-sdk-embedded-c#75]
Here's what I'm running: 
$ gcloud iot registries update basicReg --project=iotquickstart-244720 --region=us-central1 --state-pubsub-topic=projects/iotquickstart-244720/topics/status --no-enable-http-config --event-notification-config=topic=projects/iotquickstart-244720/topics/status 

$ ./iot_core_mqtt_client -p iotquickstart-244720 -d projects/iotquickstart-244720/locations/us-central1/registries/basicReg/devices/dsingalX99 -t projects/iotquickstart-244720/topics/status
Am I trying to publish to the wrong topic?

**Comment by atigyi** [comment]
The 'projects/iotquickstart-244720/topics/status' is a GCP Pub/Sub topic. A device can't directly PUBLISH on Pub/Sub topics. 

Device -> PUBLISH on MQTT topic -> GCP IoT Core -> Pub/Sub topic -> [ data sink ]

In IoT Core Registry settings see: 
"Cloud Pub/Sub topics
Cloud IoT Core routes device messages to Cloud Pub/Sub for aggregation. You can route messages to different topics and subfolders in Cloud Pub/Sub based on the type of data in the messages. [Learn more](https://cloud.google.com/iot/docs/how-tos/devices?hl=en_US&_ga=2.70207568.-1966879401.1559130072#creating_a_device_registry_with_multiple_pubsub_topics)"
Other GCP modules can then subscribe to Pub/Sub topics to consume the data.

A device is only allowed to publish MQTT messages to 'state' or 'events' MQTT topics (note MQTT topics are different than Pub/Sub topics).
So try '-t /devices/dsingalX99/state' or '-t /devices/dsingalX99/events' to successfully MQTT PUBLISH something. Data published on the 'state' topic is also stored by GCP IoT Core and can be seen on the pantheon dashboard itself.

**Comment by dhruvsus** [comment]
That worked. I wasn't aware you had to route MQTT topics to PubSub topics. Thanks!
